var a = [1, 2, 3];
var b = ['aa', 'ba', 'ca'];
var c = [4, 5, 6];
c.push(7);
c.push(8);
console.log(c);
var d = [];
d.push({ name: 'Aman', age: 18, salary: 3000 });
d.push({ name: 'Dixit', age: 28, salary: 4000 });
console.log(d);
